spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  datasource:
    username: ENC(fiwfxo+yRUr5KE2Pxi6rrbu/ud5xWzLKYYTbqtU+no0cPHxdjpn61uZC/5AKol8L)
    password: ENC(tfvDzl96dZ0jNyTxZ7nVpBZKlRD8YV+8QHp2RFMELNkict3cbar2z6W83nIKqLZw)
    url: jdbc:mysql://127.0.0.1:3306/db_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jasypt:
  encryptor:
    password: 123456
